language: php

matrix:
  include:
    - php: 7.1
    - php: 7.2
    - php: 7.3
      env:
        - ENABLE_XDEBUG=true
    - php: 7.3
      env:
        - ENABLE_DEVTOOLS=true
    - php: 7.4snapshot
    - php: nightly
  allow_failures:
    - php: 7.4snapshot
    - php: nightly
  fast_finish: true

os:
  - linux

notifications:
  irc: "chat.freenode.net#hoaproject"

sudo: false

env:
  global:
    - secure: "AAAAB3NzaC1yc2EAAAADAQABAAAAgQCt5p8gJx93Zyjy2EjIKWFPXgk76jdtrgAKPqdttMU+JoxINS40s8o/L0g0iJHy+ZXZ+AxmGQdAovJw70LBRzLV6IgRcAkZCfxwbh+H5kRV97WMfIEDnUXfZazZ5sXkmO/u9cVBYM7jZhcmdmlignNEh0v6qoFABwQdYHauymlR9w=="

cache:
  directories:
    - vendor/

before_script:
  - export PATH="$PATH:$HOME/.composer/vendor/bin"
  - if [[ ! $ENABLE_XDEBUG ]]; then
      phpenv config-rm xdebug.ini || echo "ext-xdebug is not available, cannot remove it.";
    fi

script:
  - composer install
  - vendor/bin/hoa test:run
  - if [[ $ENABLE_DEVTOOLS ]]; then
      composer global require friendsofphp/php-cs-fixer;
      vendor/bin/hoa devtools:cs --diff --dry-run .;
    fi
